export interface CharEvolution {
  oracle?: string | { text?: string; image?: string }      // 甲骨文
  bronze?: string | { text?: string; image?: string }      // 金文
  largeSeal?: string | { text?: string; image?: string }   // 大篆
  smallSeal?: string | { text?: string; image?: string }   // 小篆
  clerical?: string | { text?: string; image?: string }    // 隶书
  regular?: string | { text?: string; image?: string }     // 楷书
  simplified?: string | { text?: string; image?: string }  // 简化字
}

export interface ChineseChar {
  char: string
  pinyin: string
  radical: string
  strokeCount: number
  shuowen: string
  modernMeaning: string
  origin: string
  example: string
  animation: string
  evolution?: CharEvolution  // 汉字演化过程
}

export interface DifficultyLevel {
  id: number
  name: string
  description: string
  characters: ChineseChar[]
}

export const chineseCharacters: DifficultyLevel[] = [
  {
    id: 1,
    name: '简单',
    description: '基础汉字，笔画少，易认易写',
    characters: [
      {
        char: '一',
        pinyin: 'yī',
        radical: '一',
        strokeCount: 1,
        shuowen: '一，惟初太始，道立于一，造分天地，化成万物。',
        modernMeaning: '数字一，表示最小的正整数。也表示开始、第一。',
        origin: '一是指事字，甲骨文和金文都用一横画表示数目一。古人认为一是万物之始。',
        example: '一个、一天、第一',
        animation: 'line',
        evolution: {
          oracle: '一',
          bronze: '一',
          smallSeal: '一',
          clerical: '一',
          regular: '一',
          simplified: '一'
        }
      },
      {
        char: '二',
        pinyin: 'èr',
        radical: '二',
        strokeCount: 2,
        shuowen: '二，天地之次数也。从偶一。',
        modernMeaning: '数字二，表示数目一加一。也表示第二。',
        origin: '二是指事字，用两横画表示数目二，表示天地二数。',
        example: '二月、二个、第二',
        animation: 'lines',
        evolution: {
          oracle: '二',
          bronze: '二',
          smallSeal: '二',
          clerical: '二',
          regular: '二',
          simplified: '二'
        }
      },
      {
        char: '三',
        pinyin: 'sān',
        radical: '一',
        strokeCount: 3,
        shuowen: '三，天地人之道也。从三数。',
        modernMeaning: '数字三，表示数目二加一。也表示多次。',
        origin: '三是会意字，三横代表天、地、人三才。',
        example: '三个、三月、三思而行',
        animation: 'lines'
      },
      {
        char: '人',
        pinyin: 'rén',
        radical: '人',
        strokeCount: 2,
        shuowen: '人，天地之性最贵者也。此籀文。象臂胫之形。',
        modernMeaning: '人类，能制造工具并使用工具的高等动物。也指别人。',
        origin: '人是象形字，像人垂臂立立的形状。',
        example: '人们、人类、人山人海',
        animation: 'person'
      },
      {
        char: '大',
        pinyin: 'dà',
        radical: '大',
        strokeCount: 3,
        shuowen: '大，天大，地大，人亦大焉。象人形。',
        modernMeaning: '表示体积、面积、数量等超过一般。与"小"相对。',
        origin: '大是象形字，像一个张开双臂、顶天立地的人形。',
        example: '大人、大家、巨大',
        animation: 'person-big'
      },
      {
        char: '小',
        pinyin: 'xiǎo',
        radical: '小',
        strokeCount: 3,
        shuowen: '小，物之微也。从八，见而分之。',
        modernMeaning: '表示体积、面积等不大。也表示年幼的。',
        origin: '小是指事字，像细小的米粒形，表示微小。',
        example: '小孩、小心、小动物',
        animation: 'dots'
      },
      {
        char: '日',
        pinyin: 'rì',
        radical: '日',
        strokeCount: 4,
        shuowen: '日，实也。太阳之精不亏。从囗一。象形。',
        modernMeaning: '太阳，白天。与"夜"相对。也用于计时。',
        origin: '日是象形字，像太阳的形状，中间的一横表示太阳黑子。',
        example: '日出、日子、今日',
        animation: 'sun'
      },
      {
        char: '月',
        pinyin: 'yuè',
        radical: '月',
        strokeCount: 4,
        shuowen: '月，阙也。大阴之精。象形。',
        modernMeaning: '月球，月亮。也指月份。',
        origin: '月是象形字，像弯月的形状。',
        example: '月亮、月季、岁月',
        animation: 'moon'
      },
      {
        char: '水',
        pinyin: 'shuǐ',
        radical: '水',
        strokeCount: 4,
        shuowen: '水，准也。北方之行。象众水并流。',
        modernMeaning: '液态的水，无色无味。也指河流。',
        origin: '水是象形字，像水流蜿蜒的形状。',
        example: '水果、喝水、洪水',
        animation: 'water'
      },
      {
        char: '火',
        pinyin: 'huǒ',
        radical: '火',
        strokeCount: 4,
        shuowen: '火，毁也。南方之行，炎而上。象形。',
        modernMeaning: '燃烧产生的光和热。也指火灾。',
        origin: '火是象形字，像火焰上升的形状。',
        example: '火车、火把、火灾',
        animation: 'fire'
      },
      {
        char: '山',
        pinyin: 'shān',
        radical: '山',
        strokeCount: 3,
        shuowen: '山，宣也。宣气散，生万物。有石而高。象形。',
        modernMeaning: '地面形成的高耸部分。也指形状像山的东西。',
        origin: '山是象形字，像三座山峰并立的形状。',
        example: '高山、山顶、山河',
        animation: 'mountain'
      },
      {
        char: '石',
        pinyin: 'shí',
        radical: '石',
        strokeCount: 5,
        shuowen: '石，山石也。在厂之下。口，象形。',
        modernMeaning: '石头。也指石刻。',
        origin: '石是象形字，像山崖下的石头。',
        example: '石头、岩石、宝石',
        animation: 'stone'
      },
      {
        char: '田',
        pinyin: 'tián',
        radical: '田',
        strokeCount: 5,
        shuowen: '田，陈也。树谷曰田。象四口。十，阡陌之制也。',
        modernMeaning: '农田。也指形状像田地的。',
        origin: '田是象形字，像被分成小块的农田。',
        example: '田地、水田、田野',
        animation: 'field'
      },
      {
        char: '土',
        pinyin: 'tǔ',
        radical: '土',
        strokeCount: 3,
        shuowen: '土，地之吐生万物者也。象地之下，地之中。',
        modernMeaning: '泥土，土壤。也指土地。',
        origin: '土是象形字，像土地上面有植物生长的形状。',
        example: '土地、泥土、乡土',
        animation: 'ground'
      },
      {
        char: '口',
        pinyin: 'kǒu',
        radical: '口',
        strokeCount: 3,
        shuowen: '口，人所以言食也。象形。',
        modernMeaning: '嘴巴。也用于计数。',
        origin: '口是象形字，像张开的嘴巴形状。',
        example: '口水、门口、人口',
        animation: 'mouth'
      },
      {
        char: '目',
        pinyin: 'mù',
        radical: '目',
        strokeCount: 5,
        shuowen: '目，人眼。象形。重童子也。',
        modernMeaning: '眼睛。也用于看、审视。',
        origin: '目是象形字，像眼睛的形状。',
        example: '目光、目的、目标',
        animation: 'eye'
      },
      {
        char: '手',
        pinyin: 'shǒu',
        radical: '手',
        strokeCount: 4,
        shuowen: '手，拳也。象形。',
        modernMeaning: '手掌，也指人体上肢。',
        origin: '手是象形字，像手的形状。',
        example: '手指、左手、握手',
        animation: 'hand'
      },
      {
        char: '足',
        pinyin: 'zú',
        radical: '足',
        strokeCount: 7,
        shuowen: '足，人之足也。在下。从止、口。',
        modernMeaning: '脚。也指器物下部。',
        origin: '足是象形字，像脚的形状。',
        example: '足球、手足、满足',
        animation: 'foot'
      },
      {
        char: '刀',
        pinyin: 'dāo',
        radical: '刀',
        strokeCount: 2,
        shuowen: '刀，兵也。象形。',
        modernMeaning: '切割工具。也指形状像刀的。',
        origin: '刀是象形字，像刀的形状。',
        example: '刀子、菜刀、剪刀',
        animation: 'knife'
      },
      {
        char: '力',
        pinyin: 'lì',
        radical: '力',
        strokeCount: 2,
        shuowen: '力，筋也。象人筋之形。',
        modernMeaning: '力气。也指能力。',
        origin: '力是象形字，像手臂用力的形状。',
        example: '力气、力量、努力',
        animation: 'strength'
      },
      {
        char: '上',
        pinyin: 'shàng',
        radical: '一',
        strokeCount: 3,
        shuowen: '上，高也。此古文上，指事也。',
        modernMeaning: '高处，上面。与"下"相对。',
        origin: '上是指事字，用一横作标记，表示位置在上。',
        example: '上面、上学、上班',
        animation: 'up'
      },
      {
        char: '下',
        pinyin: 'xià',
        radical: '一',
        strokeCount: 3,
        shuowen: '下，底也。指事。',
        modernMeaning: '低处，下面。与"上"相对。',
        origin: '下是指事字，用一横作标记，表示位置在下。',
        example: '下面、下雨、下班',
        animation: 'down'
      },
      {
        char: '中',
        pinyin: 'zhōng',
        radical: '丨',
        strokeCount: 4,
        shuowen: '中，内也。从口。丨，上下通。',
        modernMeaning: '中间，内部。与"外"相对。',
        origin: '中是指事字，像旗帜正中，引申为中间。',
        example: '中国、中间、中午',
        animation: 'center'
      },
      {
        char: '天',
        pinyin: 'tiān',
        radical: '大',
        strokeCount: 4,
        shuowen: '天，颠也。至高无上，从一、大。',
        modernMeaning: '天空。也指一昼夜。',
        origin: '天是指事字，在"大"字上面加一横，表示头顶上方。',
        example: '天空、今天、明天',
        animation: 'sky'
      },
      {
        char: '气',
        pinyin: 'qì',
        radical: '气',
        strokeCount: 4,
        shuowen: '气，云气也。象形。',
        modernMeaning: '气体。也指呼吸。',
        origin: '气是象形字，像云气飘动的形状。',
        example: '空气、气体、生气',
        animation: 'cloud'
      },
      {
        char: '云',
        pinyin: 'yún',
        radical: '雨',
        strokeCount: 4,
        shuowen: '云，山川气也。从雨，云象云回转形。',
        modernMeaning: '云彩。也指说。',
        origin: '云是象形字，像云朵的形状。',
        example: '白云、云朵、乌云',
        animation: 'cloud'
      },
      {
        char: '雨',
        pinyin: 'yǔ',
        radical: '雨',
        strokeCount: 8,
        shuowen: '雨，水从云下也。一象天，冂象云，水霝其闲也。',
        modernMeaning: '从云层降下的水滴。',
        origin: '雨是象形字，像天空下雨的形状。',
        example: '下雨、雨水、雨伞',
        animation: 'rain'
      },
      {
        char: '风',
        pinyin: 'fēng',
        radical: '风',
        strokeCount: 4,
        shuowen: '风，八风也。东方曰明庶风，东南曰清明风。',
        modernMeaning: '空气流动的现象。',
        origin: '风是象形字，像风吹动的形状。',
        example: '大风、风雨、风景',
        animation: 'wind'
      },
      {
        char: '电',
        pinyin: 'diàn',
        radical: '雨',
        strokeCount: 5,
        shuowen: '电，阴阳激耀也。从雨，从申。',
        modernMeaning: '闪电。也指电力。',
        origin: '电是形声字，像闪电的形状。',
        example: '电话、电视、闪电',
        animation: 'lightning'
      },
      {
        char: '心',
        pinyin: 'xīn',
        radical: '心',
        strokeCount: 4,
        shuowen: '心，人心，土藏也。在身之中。象形。',
        modernMeaning: '心脏。也指思想。',
        origin: '心是象形字，像心脏的形状。',
        example: '心情、爱心、心脏',
        animation: 'heart'
      }
    ]
  },
  {
    id: 2,
    name: '中等',
    description: '常用汉字，笔画适中，有一定规律',
    characters: [
      {
        char: '木',
        pinyin: 'mù',
        radical: '木',
        strokeCount: 4,
        shuowen: '木，冒也。冒地而生。东方之行。从屮，下象其根。',
        modernMeaning: '树木，木材。也指枯死的。',
        origin: '木是指事字，像树木的形状，下象树根。',
        example: '树木、木头、木材',
        animation: 'tree'
      },
      {
        char: '林',
        pinyin: 'lín',
        radical: '木',
        strokeCount: 8,
        shuowen: '林，平土有丛木曰林。',
        modernMeaning: '树林。也指众多的。',
        origin: '林是会意字，两木表示树林。',
        example: '森林、树林、林木',
        animation: 'tree'
      },
      {
        char: '森',
        pinyin: 'sēn',
        radical: '木',
        strokeCount: 12,
        shuowen: '森，木多皃。从林，从木。',
        modernMeaning: '树木茂盛。也指阴暗。',
        origin: '森是会意字，三木表示森林。',
        example: '森林、森严、阴森',
        animation: 'tree'
      },
      {
        char: '花',
        pinyin: 'huā',
        radical: '艹',
        strokeCount: 7,
        shuowen: '花，草木华也。从艹，化声。',
        modernMeaning: '花朵。也指花费。',
        origin: '花是形声字，从艹表意。',
        example: '花朵、鲜花、花园',
        animation: 'flower'
      },
      {
        char: '草',
        pinyin: 'cǎo',
        radical: '艹',
        strokeCount: 9,
        shuowen: '草，草斗，栎实也。',
        modernMeaning: '草本植物。也指粗糙。',
        origin: '草是形声字，从艹表意。',
        example: '草地、小草、草原',
        animation: 'grass'
      },
      {
        char: '树',
        pinyin: 'shù',
        radical: '木',
        strokeCount: 9,
        shuowen: '树，生植之总名。从木，尌声。',
        modernMeaning: '树木。也指建立。',
        origin: '树是形声字，从木表意。',
        example: '树木、大树、树叶',
        animation: 'tree'
      },
      {
        char: '叶',
        pinyin: 'yè',
        radical: '口',
        strokeCount: 5,
        shuowen: '叶，草木之叶也。从艹，枼声。',
        modernMeaning: '叶子。也指时期。',
        origin: '叶是形声字，从口表意。',
        example: '叶子、树叶、叶片',
        animation: 'leaf'
      },
      {
        char: '根',
        pinyin: 'gēn',
        radical: '木',
        strokeCount: 10,
        shuowen: '根，木株也。从木，艮声。',
        modernMeaning: '植物的根。也指根源。',
        origin: '根是形声字，从木表意。',
        example: '树根、根本、根源',
        animation: 'root'
      },
      {
        char: '果',
        pinyin: 'guǒ',
        radical: '木',
        strokeCount: 8,
        shuowen: '果，木实也。从木，象果形在木之上。',
        modernMeaning: '果实。也指结果。',
        origin: '果是象形字，像树上结果。',
        example: '水果、苹果、果实',
        animation: 'fruit'
      },
      {
        char: '米',
        pinyin: 'mǐ',
        radical: '米',
        strokeCount: 6,
        shuowen: '米，粟实也。象禾实之形。',
        modernMeaning: '稻米。也指长度单位。',
        origin: '米是象形字，像米粒的形状。',
        example: '大米、米饭、玉米',
        animation: 'rice'
      },
      {
        char: '禾',
        pinyin: 'hé',
        radical: '禾',
        strokeCount: 5,
        shuowen: '禾，嘉谷也。二月始生，八月而孰。',
        modernMeaning: '谷类作物。也指幼苗。',
        origin: '禾是象形字，像谷穗的形状。',
        example: '禾苗、禾田、禾谷',
        animation: 'grain'
      },
      {
        char: '麦',
        pinyin: 'mài',
        radical: '麦',
        strokeCount: 7,
        shuowen: '麦，芒谷，秋孰之禾。',
        modernMeaning: '麦子。也指姓。',
        origin: '麦是象形字，像麦子的形状。',
        example: '小麦、麦子、麦田',
        animation: 'wheat'
      },
      {
        char: '豆',
        pinyin: 'dòu',
        radical: '豆',
        strokeCount: 7,
        shuowen: '豆，古食肉器也。从口，象形。',
        modernMeaning: '豆类。也指古代容器。',
        origin: '豆是象形字，像高脚容器。',
        example: '大豆、豆腐、豌豆',
        animation: 'bean'
      },
      {
        char: '瓜',
        pinyin: 'guā',
        radical: '瓜',
        strokeCount: 5,
        shuowen: '瓜，蓏也。象形。',
        modernMeaning: '瓜类植物。也指形状像瓜的。',
        origin: '瓜是象形字，像瓜的形状。',
        example: '西瓜、南瓜、黄瓜',
        animation: 'melon'
      },
      {
        char: '菜',
        pinyin: 'cài',
        radical: '艹',
        strokeCount: 11,
        shuowen: '菜，草之可食者。从艹，采声。',
        modernMeaning: '蔬菜。也指菜肴。',
        origin: '菜是形声字，从艹表意。',
        example: '蔬菜、白菜、菜园',
        animation: 'vegetable'
      },
      {
        char: '茶',
        pinyin: 'chá',
        radical: '艹',
        strokeCount: 9,
        shuowen: '茶，苦荼也。从艹，余声。',
        modernMeaning: '茶叶。也指茶树。',
        origin: '茶是形声字，从艹表意。',
        example: '茶叶、喝茶、茶水',
        animation: 'tea'
      },
      {
        char: '马',
        pinyin: 'mǎ',
        radical: '马',
        strokeCount: 3,
        shuowen: '马，怒也。武也。象马头髦尾四足之形。',
        modernMeaning: '哺乳动物。也指大的。',
        origin: '马是象形字，像马的形状。',
        example: '马车、马上、木马',
        animation: 'horse'
      },
      {
        char: '牛',
        pinyin: 'niú',
        radical: '牛',
        strokeCount: 4,
        shuowen: '牛，大牲也。牛，件也。事理也。象角头三封尾之形。',
        modernMeaning: '哺乳动物。也指固执。',
        origin: '牛是象形字，像牛头的形状。',
        example: '牛奶、牛肉、水牛',
        animation: 'cow'
      },
      {
        char: '羊',
        pinyin: 'yáng',
        radical: '羊',
        strokeCount: 6,
        shuowen: '羊，祥也。从屮，象头角四足之形。',
        modernMeaning: '哺乳动物。也指吉利。',
        origin: '羊是象形字，像羊头的形状。',
        example: '羊毛、山羊、绵羊',
        animation: 'sheep'
      },
      {
        char: '鸟',
        pinyin: 'niǎo',
        radical: '鸟',
        strokeCount: 5,
        shuowen: '鸟，长尾禽总名也。象形。',
        modernMeaning: '飞禽。也指姓氏。',
        origin: '鸟是象形字，像鸟的形状。',
        example: '小鸟、鸟儿、飞鸟',
        animation: 'bird'
      },
      {
        char: '鱼',
        pinyin: 'yú',
        radical: '鱼',
        strokeCount: 8,
        shuowen: '鱼，水虫也。象形。鱼尾与燕尾相似。',
        modernMeaning: '水生脊椎动物。也指姓氏。',
        origin: '鱼是象形字，像鱼的形状。',
        example: '鱼儿、金鱼、鲤鱼',
        animation: 'fish'
      },
      {
        char: '虫',
        pinyin: 'chóng',
        radical: '虫',
        strokeCount: 6,
        shuowen: '虫，有足谓之虫，无足谓之豸。从三虫。象形。',
        modernMeaning: '昆虫。也指动物。',
        origin: '虫是象形字，像虫的形状。',
        example: '虫子、昆虫、害虫',
        animation: 'insect'
      },
      {
        char: '鸡',
        pinyin: 'jī',
        radical: '鸟',
        strokeCount: 7,
        shuowen: '鸡，知时畜也。从隹，奚声。',
        modernMeaning: '家禽。也指生肖。',
        origin: '鸡是形声字，从鸟表意。',
        example: '小鸡、公鸡、鸡蛋',
        animation: 'chicken'
      },
      {
        char: '鸭',
        pinyin: 'yā',
        radical: '鸟',
        strokeCount: 10,
        shuowen: '鸭，鹜也。从鸟，甲声。',
        modernMeaning: '水禽。也指形状像鸭的。',
        origin: '鸭是形声字，从鸟表意。',
        example: '鸭子、鸭蛋、烤鸭',
        animation: 'duck'
      },
      {
        char: '鹅',
        pinyin: 'é',
        radical: '鸟',
        strokeCount: 12,
        shuowen: '鹅，鹜也。从鸟，我声。',
        modernMeaning: '家禽。也指形状像鹅的。',
        origin: '鹅是形声字，从鸟表意。',
        example: '白鹅、鹅毛、天鹅',
        animation: 'goose'
      },
      {
        char: '猫',
        pinyin: 'māo',
        radical: '犭',
        strokeCount: 11,
        shuowen: '猫，狸属。从豸，苗声。',
        modernMeaning: '家畜。也指形状像猫的。',
        origin: '猫是形声字，从豸表意。',
        example: '小猫、猫咪、熊猫',
        animation: 'cat'
      },
      {
        char: '狗',
        pinyin: 'gǒu',
        radical: '犭',
        strokeCount: 8,
        shuowen: '狗，犬也。从犬，句声。',
        modernMeaning: '家畜。也指形状像狗的。',
        origin: '狗是形声字，从犬表意。',
        example: '小狗、猎狗、狗粮',
        animation: 'dog'
      },
      {
        char: '猪',
        pinyin: 'zhū',
        radical: '犭',
        strokeCount: 11,
        shuowen: '猪，豕而三毛丛聚者。从犬，者声。',
        modernMeaning: '家畜。也指生肖。',
        origin: '猪是形声字，从犬表意。',
        example: '小猪、猪肉、野猪',
        animation: 'pig'
      },
      {
        char: '虎',
        pinyin: 'hǔ',
        radical: '虍',
        strokeCount: 8,
        shuowen: '虎，山兽之君。从虍，虎足象人足。',
        modernMeaning: '猛兽。也指威武的。',
        origin: '虎是象形字，像老虎的形状。',
        example: '老虎、虎牙、猛虎',
        animation: 'tiger'
      },
      {
        char: '兔',
        pinyin: 'tù',
        radical: '刀',
        strokeCount: 8,
        shuowen: '兔，兽名。象踞，后其尾形。',
        modernMeaning: '哺乳动物。也指生肖。',
        origin: '兔是象形字，像兔子的形状。',
        example: '兔子、白兔、兔毛',
        animation: 'rabbit'
      }
    ]
  },
  {
    id: 3,
    name: '难',
    description: '复杂汉字，笔画多，含义丰富',
    characters: [
      {
        char: '金',
        pinyin: 'jīn',
        radical: '金',
        strokeCount: 8,
        shuowen: '金，五色金也。黄为之长。久薶不生衣，百炼不轻。',
        modernMeaning: '金属。也指黄金。',
        origin: '金是形声字，像金属矿石的形状。',
        example: '金子、金属、黄金',
        animation: 'metal'
      },
      {
        char: '车',
        pinyin: 'chē',
        radical: '车',
        strokeCount: 4,
        shuowen: '车，舆轮之总名也。象形。',
        modernMeaning: '交通工具。也指机器。',
        origin: '车是象形字，像古代车的形状。',
        example: '汽车、火车、马车',
        animation: 'vehicle'
      },
      {
        char: '门',
        pinyin: 'mén',
        radical: '门',
        strokeCount: 3,
        shuowen: '门，闻也。从二户。象形。',
        modernMeaning: '建筑物的出入口。也指形状像门的。',
        origin: '门是象形字，像两扇门的形状。',
        example: '门口、大门、出门',
        animation: 'door'
      },
      {
        char: '户',
        pinyin: 'hù',
        radical: '户',
        strokeCount: 4,
        shuowen: '户，护也。半门曰户。象形。',
        modernMeaning: '门。也指人家。',
        origin: '户是象形字，像单扇门的形状。',
        example: '户口、门户、用户',
        animation: 'door'
      },
      {
        char: '耳',
        pinyin: 'ěr',
        radical: '耳',
        strokeCount: 6,
        shuowen: '耳，主听也。象形。',
        modernMeaning: '耳朵。也指形状像耳的。',
        origin: '耳是象形字，像耳朵的形状。',
        example: '耳朵、耳机、木耳',
        animation: 'ear'
      },
      {
        char: '弓',
        pinyin: 'gōng',
        radical: '弓',
        strokeCount: 3,
        shuowen: '弓，以近穷远。象形。',
        modernMeaning: '射箭的器具。也指形状像弓的。',
        origin: '弓是象形字，像弓的形状。',
        example: '弓箭、弹弓、弓形',
        animation: 'bow'
      },
      {
        char: '矢',
        pinyin: 'shǐ',
        radical: '矢',
        strokeCount: 5,
        shuowen: '矢，弓弩矢也。从入，象镝栝羽之形。',
        modernMeaning: '箭。也指正直。',
        origin: '矢是象形字，像箭的形状。',
        example: '箭头、矢口、流矢',
        animation: 'arrow'
      },
      {
        char: '衣',
        pinyin: 'yī',
        radical: '衣',
        strokeCount: 6,
        shuowen: '衣，依也。上曰衣，下曰裳。象覆二人之形。',
        modernMeaning: '衣服。也指果皮。',
        origin: '衣是象形字，像衣服的形状。',
        example: '衣服、上衣、毛衣',
        animation: 'clothes'
      },
      {
        char: '食',
        pinyin: 'shí',
        radical: '食',
        strokeCount: 9,
        shuowen: '食，一米也。从皀，亼声。',
        modernMeaning: '吃。也指食物。',
        origin: '食是象形字，像食物的形状。',
        example: '食物、食品、粮食',
        animation: 'food'
      },
      {
        char: '贝',
        pinyin: 'bèi',
        radical: '贝',
        strokeCount: 4,
        shuowen: '贝，海介虫也。居陆名猋，在水名函。象形。',
        modernMeaning: '贝壳。也指货币。',
        origin: '贝是象形字，像贝壳的形状。',
        example: '贝壳、宝贝、分贝',
        animation: 'shell'
      },
      {
        char: '王',
        pinyin: 'wáng',
        radical: '王',
        strokeCount: 4,
        shuowen: '王，天下所归往也。董仲舒曰：古之造文者，三画而连其中谓之王。',
        modernMeaning: '君主。也指最大的。',
        origin: '王是象形字，像斧钺的形状，象征权力。',
        example: '国王、王子、大王',
        animation: 'king'
      },
      {
        char: '玉',
        pinyin: 'yù',
        radical: '玉',
        strokeCount: 5,
        shuowen: '玉，石之美。象三玉之连。丨，其贯也。',
        modernMeaning: '玉石。也指美好的。',
        origin: '玉是象形字，像串起来的玉石。',
        example: '玉石、玉米、宝玉',
        animation: 'jade'
      },
      {
        char: '生',
        pinyin: 'shēng',
        radical: '生',
        strokeCount: 5,
        shuowen: '生，进也。象草木生出土上。',
        modernMeaning: '生长。也指生命。',
        origin: '生是象形字，像草木生长的形状。',
        example: '生命、生活、生日',
        animation: 'grow'
      },
      {
        char: '出',
        pinyin: 'chū',
        radical: '凵',
        strokeCount: 5,
        shuowen: '出，进也。象草木益滋，上出达也。',
        modernMeaning: '从里面到外面。与"入"相对。',
        origin: '出是象形字，像脚从洞穴走出的形状。',
        example: '出门、出去、出现',
        animation: 'exit'
      },
      {
        char: '入',
        pinyin: 'rù',
        radical: '入',
        strokeCount: 2,
        shuowen: '入，内也。象从上俱下也。',
        modernMeaning: '从外面到里面。与"出"相对。',
        origin: '入是象形字，像进入的形状。',
        example: '入门、进入、入学',
        animation: 'enter'
      },
      {
        char: '开',
        pinyin: 'kāi',
        radical: '廾',
        strokeCount: 4,
        shuowen: '开，张也。从门，从开。',
        modernMeaning: '打开。与"关"相对。',
        origin: '开是象形字，像开门的形状。',
        example: '开门、开心、开始',
        animation: 'open'
      },
      {
        char: '关',
        pinyin: 'guān',
        radical: '丷',
        strokeCount: 6,
        shuowen: '关，以木横持门户也。从门，丱声。',
        modernMeaning: '闭合。也指关联。',
        origin: '关是形声字，像门闩的形状。',
        example: '关门、关心、关系',
        animation: 'close'
      },
      {
        char: '坐',
        pinyin: 'zuò',
        radical: '土',
        strokeCount: 7,
        shuowen: '坐，止也。从土，从畱省。土，所止也。',
        modernMeaning: '坐下。也指乘坐。',
        origin: '坐是象形字，像两人坐在土上的形状。',
        example: '坐下、坐车、坐落',
        animation: 'sit'
      },
      {
        char: '立',
        pinyin: 'lì',
        radical: '立',
        strokeCount: 5,
        shuowen: '立，住也。从大立一之上。',
        modernMeaning: '站立。也指建立。',
        origin: '立是象形字，像人站立的形状。',
        example: '立正、成立、独立',
        animation: 'stand'
      },
      {
        char: '走',
        pinyin: 'zǒu',
        radical: '走',
        strokeCount: 7,
        shuowen: '走，趋也。从夭、止。夭止者，屈也。',
        modernMeaning: '行走。也指跑。',
        origin: '走是象形字，像人摆动手臂奔跑的形状。',
        example: '走路、行走、奔走',
        animation: 'walk'
      },
      {
        char: '跑',
        pinyin: 'pǎo',
        radical: '足',
        strokeCount: 12,
        shuowen: '跑，足跑也。从足，包声。',
        modernMeaning: '快速奔跑。',
        origin: '跑是形声字，从足表意。',
        example: '跑步、奔跑、跑腿',
        animation: 'run'
      },
      {
        char: '跳',
        pinyin: 'tiào',
        radical: '足',
        strokeCount: 13,
        shuowen: '跳，蹶也。从足，兆声。',
        modernMeaning: '跳跃。也指越过。',
        origin: '跳是形声字，从足表意。',
        example: '跳绳、跳水、心跳',
        animation: 'jump'
      },
      {
        char: '飞',
        pinyin: 'fēi',
        radical: '飞',
        strokeCount: 3,
        shuowen: '飞，鸟翥也。象形。',
        modernMeaning: '鸟类在空中活动。也指快速的。',
        origin: '飞是象形字，像鸟飞翔的形状。',
        example: '飞机、飞行、飞翔',
        animation: 'fly'
      },
      {
        char: '高',
        pinyin: 'gāo',
        radical: '高',
        strokeCount: 10,
        shuowen: '高，崇也。象台观高之形。从门、口。与仓、舍同意。',
        modernMeaning: '从下向上距离大。与"低"相对。',
        origin: '高是象形字，像高台的形状。',
        example: '高山、高兴、高大',
        animation: 'tall'
      },
      {
        char: '低',
        pinyin: 'dī',
        radical: '亻',
        strokeCount: 7,
        shuowen: '低，下也。从人，从氐。',
        modernMeaning: '从下向上距离小。与"高"相对。',
        origin: '低是形声字，从人表意。',
        example: '低头、低处、高低',
        animation: 'low'
      },
      {
        char: '长',
        pinyin: 'cháng',
        radical: '长',
        strokeCount: 4,
        shuowen: '长，久远也。从兀，从匕。',
        modernMeaning: '两点距离大。与"短"相对。',
        origin: '长是象形字，像长发的形状。',
        example: '长短、长江、长久',
        animation: 'long'
      },
      {
        char: '短',
        pinyin: 'duǎn',
        radical: '矢',
        strokeCount: 12,
        shuowen: '短，有所长短，以矢为正。从矢，豆声。',
        modernMeaning: '两点距离小。与"长"相对。',
        origin: '短是形声字，从矢表意。',
        example: '长短、短小、短暂',
        animation: 'short'
      },
      {
        char: '多',
        pinyin: 'duō',
        radical: '夕',
        strokeCount: 6,
        shuowen: '多，重也。从重夕。夕者，相绎也，故为多。',
        modernMeaning: '数量大。与"少"相对。',
        origin: '多是会意字，两个夕表示重复。',
        example: '多少、很多、多数',
        animation: 'many'
      },
      {
        char: '少',
        pinyin: 'shǎo',
        radical: '小',
        strokeCount: 4,
        shuowen: '少，不多也。从小，丿声。',
        modernMeaning: '数量小。与"多"相对。',
        origin: '少是象形字，像细小的形状。',
        example: '多少、少数、缺少',
        animation: 'few'
      },
      {
        char: '白',
        pinyin: 'bái',
        radical: '白',
        strokeCount: 5,
        shuowen: '白，西方色也。阴用事，物色白。从入合二。',
        modernMeaning: '像霜雪的颜色。也指清楚。',
        origin: '白是象形字，像太阳初升的形状。',
        example: '白色、白云、明白',
        animation: 'white'
      },
      {
        char: '黑',
        pinyin: 'hēi',
        radical: '黑',
        strokeCount: 12,
        shuowen: '黑，火所熏之色也。从炎上出。',
        modernMeaning: '像煤烟的颜色。也指黑暗的。',
        origin: '黑是象形字，像被烟熏黑的形状。',
        example: '黑色、黑夜、黑板',
        animation: 'black'
      },
      {
        char: '红',
        pinyin: 'hóng',
        radical: '纟',
        strokeCount: 6,
        shuowen: '红，帛赤白色也。从糸，工声。',
        modernMeaning: '像鲜血的颜色。也指喜庆。',
        origin: '红是形声字，从糸表意。',
        example: '红色、红花、火红',
        animation: 'red'
      },
      {
        char: '绿',
        pinyin: 'lǜ',
        radical: '纟',
        strokeCount: 11,
        shuowen: '绿，帛青黄色也。从糸，录声。',
        modernMeaning: '像草叶的颜色。也指环保。',
        origin: '绿是形声字，从糸表意。',
        example: '绿色、绿叶、碧绿',
        animation: 'green'
      },
      {
        char: '黄',
        pinyin: 'huáng',
        radical: '黄',
        strokeCount: 11,
        shuowen: '黄，地之色也。从田，从炗。',
        modernMeaning: '像金色的颜色。也指黄帝。',
        origin: '黄是象形字，像人佩戴玉佩的形状。',
        example: '黄色、黄金、黄瓜',
        animation: 'yellow'
      },
      {
        char: '蓝',
        pinyin: 'lán',
        radical: '艹',
        strokeCount: 13,
        shuowen: '蓝，染青草也。从艹，监声。',
        modernMeaning: '像天空的颜色。也指植物。',
        origin: '蓝是形声字，从艹表意。',
        example: '蓝色、蓝天、蓝莓',
        animation: 'blue'
      },
      {
        char: '紫',
        pinyin: 'zǐ',
        radical: '糸',
        strokeCount: 12,
        shuowen: '紫，帛青赤色也。从糸，此声。',
        modernMeaning: '蓝红混合色。也指高贵。',
        origin: '紫是形声字，从糸表意。',
        example: '紫色、紫菜、万紫千红',
        animation: 'purple'
      },
      {
        char: '方',
        pinyin: 'fāng',
        radical: '方',
        strokeCount: 4,
        shuowen: '方，并船也。象两舟总头形。',
        modernMeaning: '四角都是直角的四边形。也指方向。',
        origin: '方是象形字，像并船的形状。',
        example: '方向、方正、方法',
        animation: 'square'
      },
      {
        char: '圆',
        pinyin: 'yuán',
        radical: '囗',
        strokeCount: 10,
        shuowen: '圆，圜全也。从囗，员声。',
        modernMeaning: '圆形。也指完备。',
        origin: '圆是形声字，从囗表意。',
        example: '圆形、团圆、圆满',
        animation: 'circle'
      },
      {
        char: '角',
        pinyin: 'jiǎo',
        radical: '角',
        strokeCount: 7,
        shuowen: '角，兽角也。象形。',
        modernMeaning: '兽角。也指几何图形。',
        origin: '角是象形字，像兽角的形状。',
        example: '角度、牛角、直角',
        animation: 'horn'
      },
      {
        char: '直',
        pinyin: 'zhí',
        radical: '目',
        strokeCount: 8,
        shuowen: '直，正见也。从十、目、乚。',
        modernMeaning: '不弯曲。也指公正。',
        origin: '直是象形字，像眼睛正视的形状。',
        example: '直线、直接、正直',
        animation: 'straight'
      },
      {
        char: '弯',
        pinyin: 'wān',
        radical: '弓',
        strokeCount: 9,
        shuowen: '弯，持弓关矢也。从弓，䜌声。',
        modernMeaning: '不直。也指使弯曲。',
        origin: '弯是形声字，从弓表意。',
        example: '弯曲、弯路、弯腰',
        animation: 'curve'
      },
      {
        char: '平',
        pinyin: 'píng',
        radical: '干',
        strokeCount: 5,
        shuowen: '平，语平舒也。从亏，从八。',
        modernMeaning: '不倾斜。也指安定。',
        origin: '平是象形字，像气息平舒的形状。',
        example: '平安、平时、和平',
        animation: 'flat'
      },
      {
        char: '安',
        pinyin: 'ān',
        radical: '宀',
        strokeCount: 6,
        shuowen: '安，静也。从女在宀下。',
        modernMeaning: '安全。也指安定。',
        origin: '安是会意字，女子在屋下表示安全。',
        example: '安全、安心、平安',
        animation: 'safe'
      },
      {
        char: '全',
        pinyin: 'quán',
        radical: '入',
        strokeCount: 6,
        shuowen: '全，完也。从入，从工。',
        modernMeaning: '完备。也指整个。',
        origin: '全是会意字，像完整的玉器。',
        example: '完全、全部、全国',
        animation: 'complete'
      },
      {
        char: '好',
        pinyin: 'hǎo',
        radical: '女',
        strokeCount: 6,
        shuowen: '好，美也。从女、子。',
        modernMeaning: '优点多的。与"坏"相对。',
        origin: '好是会意字，女子抱着孩子表示美好。',
        example: '好人、好处、美好',
        animation: 'good'
      },
      {
        char: '美',
        pinyin: 'měi',
        radical: '羊',
        strokeCount: 9,
        shuowen: '美，甘也。从羊，从大。',
        modernMeaning: '好看。也指得意。',
        origin: '美是会意字，羊大则味美。',
        example: '美丽、美好、完美',
        animation: 'beautiful'
      },
      {
        char: '丽',
        pinyin: 'lì',
        radical: '一',
        strokeCount: 7,
        shuowen: '丽，旅行也。鹿非常美丽。从鹿，丽声。',
        modernMeaning: '好看。也指附着。',
        origin: '丽是象形字，像鹿美丽的形状。',
        example: '美丽、华丽、壮丽',
        animation: 'beautiful'
      },
      {
        char: '亮',
        pinyin: 'liàng',
        radical: '亠',
        strokeCount: 9,
        shuowen: '亮，明也。从人，从高省。',
        modernMeaning: '明亮。也指清楚。',
        origin: '亮是形声字，表示明亮。',
        example: '明亮、响亮、漂亮',
        animation: 'bright'
      },
      {
        char: '明',
        pinyin: 'míng',
        radical: '日',
        strokeCount: 8,
        shuowen: '明，照也。从月，从囧。',
        modernMeaning: '明亮。也指清楚。',
        origin: '明是会意字，日月交辉表示明亮。',
        example: '明天、明白、光明',
        animation: 'bright'
      },
      {
        char: '光',
        pinyin: 'guāng',
        radical: '儿',
        strokeCount: 6,
        shuowen: '光，明也。从火在人上，光明意也。',
        modernMeaning: '光线。也指光彩。',
        origin: '光是会意字，火在人上表示光明。',
        example: '光明、阳光、时光',
        animation: 'light'
      },
      {
        char: '文',
        pinyin: 'wén',
        radical: '文',
        strokeCount: 4,
        shuowen: '文，错画也。象交文。',
        modernMeaning: '文字。也指文化。',
        origin: '文是象形字，像纹理的形状。',
        example: '文化、文字、文章',
        animation: 'culture'
      },
      {
        char: '字',
        pinyin: 'zì',
        radical: '子',
        strokeCount: 6,
        shuowen: '字，乳也。从子在宀下。',
        modernMeaning: '文字。也指生育。',
        origin: '字是象形字，屋内有子表示生育。',
        example: '文字、字母、名字',
        animation: 'character'
      },
      {
        char: '书',
        pinyin: 'shū',
        radical: '乛',
        strokeCount: 4,
        shuowen: '书，箸也。从聿，者声。',
        modernMeaning: '书籍。也指写字。',
        origin: '书是形声字，像手拿笔写字。',
        example: '书本、读书、书法',
        animation: 'book'
      },
      {
        char: '画',
        pinyin: 'huà',
        radical: '田',
        strokeCount: 8,
        shuowen: '画，界也。象田四界。聿，所以画之。',
        modernMeaning: '绘画。也指图画。',
        origin: '画是象形字，像划分田界的形状。',
        example: '画画、画家、国画',
        animation: 'paint'
      },
      {
        char: '诗',
        pinyin: 'shī',
        radical: '讠',
        strokeCount: 8,
        shuowen: '诗，志也。从言，寺声。',
        modernMeaning: '诗歌。也指诗经。',
        origin: '诗是形声字，从言表意。',
        example: '诗歌、诗人、古诗',
        animation: 'poem'
      },
      {
        char: '歌',
        pinyin: 'gē',
        radical: '欠',
        strokeCount: 14,
        shuowen: '歌，咏也。从欠，哥声。',
        modernMeaning: '歌曲。也指唱。',
        origin: '歌是形声字，从欠表意。',
        example: '唱歌、歌曲、歌声',
        animation: 'song'
      },
      {
        char: '乐',
        pinyin: 'lè',
        radical: '丿',
        strokeCount: 5,
        shuowen: '乐，五声八音总名。象鼓鞞。',
        modernMeaning: '快乐。也指音乐。',
        origin: '乐是象形字，像乐器的形状。',
        example: '快乐、音乐、乐趣',
        animation: 'happy'
      },
      {
        char: '学',
        pinyin: 'xué',
        radical: '子',
        strokeCount: 8,
        shuowen: '学，觉悟也。从教，从冖。',
        modernMeaning: '学习。也指学问。',
        origin: '学是象形字，像双手摆弄算筹。',
        example: '学习、学生、学校',
        animation: 'learn'
      },
      {
        char: '习',
        pinyin: 'xí',
        radical: '乙',
        strokeCount: 3,
        shuowen: '习，数飞也。从羽，与声。',
        modernMeaning: '练习。也指习惯。',
        origin: '习是象形字，像鸟练习飞翔。',
        example: '学习、习惯、复习',
        animation: 'practice'
      },
      {
        char: '老',
        pinyin: 'lǎo',
        radical: '老',
        strokeCount: 6,
        shuowen: '老，考也。七十曰老。从人、毛、匕。',
        modernMeaning: '年岁大。与"少"相对。',
        origin: '老是象形字，像老人驼背的形状。',
        example: '老师、老人、老年',
        animation: 'old'
      },
      {
        char: '师',
        pinyin: 'shī',
        radical: '巾',
        strokeCount: 6,
        shuowen: '师，二千五百人为师。从帀，从𠂤。',
        modernMeaning: '老师。也指军队。',
        origin: '师是象形字，像军队的形状。',
        example: '老师、师傅、师长',
        animation: 'teacher'
      },
      {
        char: '爸',
        pinyin: 'bà',
        radical: '父',
        strokeCount: 8,
        shuowen: '爸，父也。从父，巴声。',
        modernMeaning: '父亲。',
        origin: '爸是形声字，从父表意。',
        example: '爸爸、爸妈、老爸',
        animation: 'father'
      },
      {
        char: '妈',
        pinyin: 'mā',
        radical: '女',
        strokeCount: 6,
        shuowen: '妈，母也。从女，马声。',
        modernMeaning: '母亲。',
        origin: '妈是形声字，从女表意。',
        example: '妈妈、妈父、老妈',
        animation: 'mother'
      },
      {
        char: '家',
        pinyin: 'jiā',
        radical: '宀',
        strokeCount: 10,
        shuowen: '家，居也。从宀，豭省声。',
        modernMeaning: '家庭。也指住所。',
        origin: '家是象形字，屋内有猪表示家。',
        example: '家庭、家人、回家',
        animation: 'home'
      },
      {
        char: '国',
        pinyin: 'guó',
        radical: '囗',
        strokeCount: 8,
        shuowen: '国，邦也。从囗，从或。',
        modernMeaning: '国家。也指国都。',
        origin: '国是象形字，像城墙内有土地。',
        example: '国家、中国、国旗',
        animation: 'country'
      },
      {
        char: '爱',
        pinyin: 'ài',
        radical: '爫',
        strokeCount: 10,
        shuowen: '爱，行皃。从夊，㤅声。',
        modernMeaning: '喜爱。也指爱情。',
        origin: '爱是形声字，表示喜爱。',
        example: '爱心、爱护、热爱',
        animation: 'love'
      },
      {
        char: '情',
        pinyin: 'qíng',
        radical: '忄',
        strokeCount: 11,
        shuowen: '情，人之阴气有欲者。从心，青声。',
        modernMeaning: '感情。也指情况。',
        origin: '情是形声字，从心表意。',
        example: '情感、心情、友情',
        animation: 'emotion'
      },
      {
        char: '友',
        pinyin: 'yǒu',
        radical: '又',
        strokeCount: 4,
        shuowen: '友，同志为友。从二又。',
        modernMeaning: '朋友。也指友好。',
        origin: '友是象形字，像两只手相握。',
        example: '朋友、友情、友谊',
        animation: 'friend'
      },
      {
        char: '春',
        pinyin: 'chūn',
        radical: '日',
        strokeCount: 9,
        shuowen: '春，推也。从艹，从日，艹春时生也。',
        modernMeaning: '春季。也指生机。',
        origin: '春是象形字，像草木春天生长。',
        example: '春天、春节、青春',
        animation: 'spring'
      },
      {
        char: '夏',
        pinyin: 'xià',
        radical: '夂',
        strokeCount: 10,
        shuowen: '夏，中国之人也。从夊，从页。',
        modernMeaning: '夏季。也指华夏。',
        origin: '夏是象形字，像人形。',
        example: '夏天、夏季、华夏',
        animation: 'summer'
      },
      {
        char: '秋',
        pinyin: 'qiū',
        radical: '禾',
        strokeCount: 9,
        shuowen: '秋，禾谷孰也。从禾，从省声。',
        modernMeaning: '秋季。也指年。',
        origin: '秋是象形字，像蟋蟀的形状。',
        example: '秋天、秋季、秋风',
        animation: 'autumn'
      },
      {
        char: '冬',
        pinyin: 'dōng',
        radical: '夂',
        strokeCount: 5,
        shuowen: '冬，四时尽也。从夂，从仌。',
        modernMeaning: '冬季。也指终了。',
        origin: '冬是象形字，像绳子两端打结。',
        example: '冬天、冬季、冬至',
        animation: 'winter'
      },
      {
        char: '早',
        pinyin: 'zǎo',
        radical: '日',
        strokeCount: 6,
        shuowen: '早，晨也。从日在甲上。',
        modernMeaning: '早晨。与"晚"相对。',
        origin: '早是象形字，太阳刚升起。',
        example: '早上、早晨、早安',
        animation: 'sun'
      },
      {
        char: '晚',
        pinyin: 'wǎn',
        radical: '日',
        strokeCount: 11,
        shuowen: '晚，莫也。从日，免声。',
        modernMeaning: '晚上。与"早"相对。',
        origin: '晚是形声字，从日表意。',
        example: '晚上、夜晚、晚安',
        animation: 'moon'
      },
      {
        char: '午',
        pinyin: 'wǔ',
        radical: '十',
        strokeCount: 4,
        shuowen: '午，牾也。五月阴气午逆阳。',
        modernMeaning: '中午。也指地支第七位。',
        origin: '午是象形字，像舂米的杵。',
        example: '中午、上午、下午',
        animation: 'sun'
      },
      {
        char: '年',
        pinyin: 'nián',
        radical: '干',
        strokeCount: 6,
        shuowen: '年，谷孰也。从禾，千声。',
        modernMeaning: '时间单位。也指年龄。',
        origin: '年是象形字，像人背着谷物。',
        example: '年级、新年、年轻',
        animation: 'grain'
      },
      {
        char: '星',
        pinyin: 'xīng',
        radical: '日',
        strokeCount: 9,
        shuowen: '星，万物之精，上为列星。',
        modernMeaning: '星星。也指细小的。',
        origin: '星是形声字，从日表意。',
        example: '星星、星球、明星',
        animation: 'star'
      },
      {
        char: '空',
        pinyin: 'kōng',
        radical: '穴',
        strokeCount: 8,
        shuowen: '空，窍也。从穴，工声。',
        modernMeaning: '空虚。也指天空。',
        origin: '空是形声字，从穴表意。',
        example: '空气、天空、空间',
        animation: 'cloud'
      },
      {
        char: '地',
        pinyin: 'dì',
        radical: '土',
        strokeCount: 6,
        shuowen: '地，元气初分，轻清阳为天，重浊阴为地。',
        modernMeaning: '大地。也指土地。',
        origin: '地是形声字，从土表意。',
        example: '地球、地方、土地',
        animation: 'ground'
      },
      {
        char: '河',
        pinyin: 'hé',
        radical: '氵',
        strokeCount: 8,
        shuowen: '河，水出敦煌塞外昆仑山，发原注海。',
        modernMeaning: '河流。也指银河。',
        origin: '河是形声字，从水表意。',
        example: '河流、河水、黄河',
        animation: 'river'
      },
      {
        char: '海',
        pinyin: 'hǎi',
        radical: '氵',
        strokeCount: 10,
        shuowen: '海，天池也。以纳百川者。从水，每声。',
        modernMeaning: '大洋靠近陆地的部分。也指大的湖泊。',
        origin: '海是形声字，从水表意，每表声。',
        example: '海洋、大海、海水',
        animation: 'ocean'
      },
      {
        char: '湖',
        pinyin: 'hú',
        radical: '氵',
        strokeCount: 12,
        shuowen: '海，大陂也。从水，胡声。',
        modernMeaning: '湖泊。也指湖南湖北。',
        origin: '湖是形声字，从水表意。',
        example: '湖水、西湖、湖泊',
        animation: 'ocean'
      },
      {
        char: '洋',
        pinyin: 'yáng',
        radical: '氵',
        strokeCount: 9,
        shuowen: '洋，水名。从水，羊声。',
        modernMeaning: '海洋。也指盛大。',
        origin: '洋是形声字，从水表意。',
        example: '海洋、大洋、洋溢',
        animation: 'ocean'
      },
      {
        char: '波',
        pinyin: 'bō',
        radical: '氵',
        strokeCount: 8,
        shuowen: '波，水涌流也。从水，皮声。',
        modernMeaning: '波浪。也指起伏。',
        origin: '波是形声字，从水表意。',
        example: '波浪、波涛、波动',
        animation: 'water'
      },
      {
        char: '浪',
        pinyin: 'làng',
        radical: '氵',
        strokeCount: 10,
        shuowen: '浪，沧浪水也。从水，良声。',
        modernMeaning: '波浪。也指放纵。',
        origin: '浪是形声字，从水表意。',
        example: '浪花、海浪、浪费',
        animation: 'water'
      },
      {
        char: '沙',
        pinyin: 'shā',
        radical: '氵',
        strokeCount: 7,
        shuowen: '沙，水散石也。从水，从少。',
        modernMeaning: '沙子。也指细小。',
        origin: '沙是会意字，水少为沙。',
        example: '沙子、沙滩、风沙',
        animation: 'dots'
      },
      {
        char: '泥',
        pinyin: 'ní',
        radical: '氵',
        strokeCount: 8,
        shuowen: '泥，水出北地郁郅北蛮中。从水，尼声。',
        modernMeaning: '泥土。也指涂抹。',
        origin: '泥是形声字，从水表意。',
        example: '泥土、水泥、泥泞',
        animation: 'ground'
      },
      {
        char: '冰',
        pinyin: 'bīng',
        radical: '冫',
        strokeCount: 6,
        shuowen: '冰，水坚也。从仌，从水。',
        modernMeaning: '水凝结成的固体。也指冷淡。',
        origin: '冰是会意字，水凝结成冰。',
        example: '冰块、冰雪、结冰',
        animation: 'snow'
      },
      {
        char: '雪',
        pinyin: 'xuě',
        radical: '雨',
        strokeCount: 11,
        shuowen: '雪，凝雨说物者。从雨，彗声。',
        modernMeaning: '雪花。也指洗刷。',
        origin: '雪是形声字，从雨表意。',
        example: '雪花、下雪、雪人',
        animation: 'snow'
      },
      {
        char: '雷',
        pinyin: 'léi',
        radical: '雨',
        strokeCount: 13,
        shuowen: '雷，阴阳薄动雷雨生物者也。从雨，晶象回转形。',
        modernMeaning: '雷电。也指爆炸。',
        origin: '雷是象形字，像雷声滚动。',
        example: '雷电、打雷、雷雨',
        animation: 'lightning'
      },
      {
        char: '电',
        pinyin: 'diàn',
        radical: '雨',
        strokeCount: 5,
        shuowen: '电，阴阳激耀也。从雨，从申。',
        modernMeaning: '闪电。也指电力。',
        origin: '电是形声字，像闪电的形状。',
        example: '电话、电视、闪电',
        animation: 'lightning'
      },
      {
        char: '光',
        pinyin: 'guāng',
        radical: '儿',
        strokeCount: 6,
        shuowen: '光，明也。从火在人上，光明意也。',
        modernMeaning: '光线。也指荣誉。',
        origin: '光是会意字，火在人上表示光明。',
        example: '光明、阳光、灯光',
        animation: 'sun'
      },
      {
        char: '明',
        pinyin: 'míng',
        radical: '日',
        strokeCount: 8,
        shuowen: '明，照也。从月从囧。',
        modernMeaning: '明亮。也指清楚。',
        origin: '明是会意字，日月为明。',
        example: '明天、明白、光明',
        animation: 'sun'
      },
      {
        char: '亮',
        pinyin: 'liàng',
        radical: '亠',
        strokeCount: 9,
        shuowen: '亮，明也。从儿从高省。',
        modernMeaning: '明亮。也指响亮。',
        origin: '亮是形声字，表示明亮。',
        example: '明亮、响亮、漂亮',
        animation: 'sun'
      },
      {
        char: '暗',
        pinyin: 'àn',
        radical: '日',
        strokeCount: 13,
        shuowen: '暗，日无光也。从日，音声。',
        modernMeaning: '昏暗。也指秘密。',
        origin: '暗是形声字，从日表意。',
        example: '黑暗、暗示、阴暗',
        animation: 'moon'
      },
      {
        char: '黑',
        pinyin: 'hēi',
        radical: '黑',
        strokeCount: 12,
        shuowen: '黑，火所熏之色也。从炎上出。',
        modernMeaning: '黑色。也指黑暗。',
        origin: '黑是象形字，像被熏黑的形状。',
        example: '黑色、黑暗、黑板',
        animation: 'dots'
      },
      {
        char: '白',
        pinyin: 'bái',
        radical: '白',
        strokeCount: 5,
        shuowen: '白，西方色也。阴用事，物色白。',
        modernMeaning: '白色。也指清楚。',
        origin: '白是象形字，像太阳初升。',
        example: '白色、白云、白天',
        animation: 'sun'
      },
      {
        char: '红',
        pinyin: 'hóng',
        radical: '纟',
        strokeCount: 6,
        shuowen: '红，帛赤白色也。从糸，工声。',
        modernMeaning: '红色。也指成功。',
        origin: '红是形声字，从糸表意。',
        example: '红色、红花、火红',
        animation: 'fire'
      },
      {
        char: '绿',
        pinyin: 'lǜ',
        radical: '纟',
        strokeCount: 11,
        shuowen: '绿，帛青黄色也。从糸，录声。',
        modernMeaning: '绿色。也指环保。',
        origin: '绿是形声字，从糸表意。',
        example: '绿色、绿叶、绿化',
        animation: 'tree'
      },
      {
        char: '黄',
        pinyin: 'huáng',
        radical: '黄',
        strokeCount: 11,
        shuowen: '黄，地之色也。从田从炗，炗亦声。',
        modernMeaning: '黄色。也指黄金。',
        origin: '黄是象形字，像人佩玉。',
        example: '黄色、黄河、黄金',
        animation: 'sun'
      },
      {
        char: '蓝',
        pinyin: 'lán',
        radical: '艹',
        strokeCount: 13,
        shuowen: '蓝，染青草也。从艹，监声。',
        modernMeaning: '蓝色。也指蓼蓝。',
        origin: '蓝是形声字，从艹表意。',
        example: '蓝色、蓝天、蓝图',
        animation: 'sky'
      },
      {
        char: '紫',
        pinyin: 'zǐ',
        radical: '糸',
        strokeCount: 12,
        shuowen: '紫，帛青赤色也。从糸，此声。',
        modernMeaning: '紫色。也指祥瑞。',
        origin: '紫是形声字，从糸表意。',
        example: '紫色、紫菜、万紫千红',
        animation: 'flower'
      },
      {
        char: '金',
        pinyin: 'jīn',
        radical: '金',
        strokeCount: 8,
        shuowen: '金，五色金也。黄为之长。久薶不生衣，百炼不轻。',
        modernMeaning: '金属。也指黄金。',
        origin: '金是象形字，像金属矿石的形状。',
        example: '金子、金属、黄金',
        animation: 'metal'
      },
      {
        char: '银',
        pinyin: 'yín',
        radical: '钅',
        strokeCount: 11,
        shuowen: '银，白金也。从金，艮声。',
        modernMeaning: '白银。也指银行。',
        origin: '银是形声字，从金表意。',
        example: '银行、白银、银河',
        animation: 'metal'
      },
      {
        char: '铜',
        pinyin: 'tóng',
        radical: '钅',
        strokeCount: 11,
        shuowen: '铜，赤金也。从金，同声。',
        modernMeaning: '铜金属。也指铜器。',
        origin: '铜是形声字，从金表意。',
        example: '铜钱、青铜、铜像',
        animation: 'metal'
      },
      {
        char: '铁',
        pinyin: 'tiě',
        radical: '钅',
        strokeCount: 10,
        shuowen: '铁，黑金也。从金，失声。',
        modernMeaning: '铁金属。也指坚硬。',
        origin: '铁是形声字，从金表意。',
        example: '钢铁、铁路、铁塔',
        animation: 'metal'
      },
      {
        char: '木',
        pinyin: 'mù',
        radical: '木',
        strokeCount: 4,
        shuowen: '木，冒也。冒地而生。东方之行。从屮，下象其根。',
        modernMeaning: '树木，木材。也指枯死的。',
        origin: '木是指事字，像树木的形状，下象树根。',
        example: '树木、木头、木材',
        animation: 'tree'
      },
      {
        char: '竹',
        pinyin: 'zhú',
        radical: '竹',
        strokeCount: 6,
        shuowen: '竹，冬生草也。象形。',
        modernMeaning: '竹子。也指竹器。',
        origin: '竹是象形字，像竹枝竹叶。',
        example: '竹子、竹林、竹叶',
        animation: 'tree'
      },
      {
        char: '米',
        pinyin: 'mǐ',
        radical: '米',
        strokeCount: 6,
        shuowen: '米，粟实也。象禾实之形。',
        modernMeaning: '稻米。也指长度单位。',
        origin: '米是象形字，像米粒的形状。',
        example: '大米、米饭、玉米',
        animation: 'rice'
      },
      {
        char: '面',
        pinyin: 'miàn',
        radical: '面',
        strokeCount: 9,
        shuowen: '面，颜前也。从𦣻，象人面形。',
        modernMeaning: '脸。也指表面。',
        origin: '面是象形字，像人脸的形状。',
        example: '面包、面条、面对',
        animation: 'mouth'
      },
      {
        char: '饭',
        pinyin: 'fàn',
        radical: '饣',
        strokeCount: 7,
        shuowen: '饭，食也。从食，反声。',
        modernMeaning: '煮熟的谷类。也指餐食。',
        origin: '饭是形声字，从食表意。',
        example: '吃饭、米饭、饭菜',
        animation: 'rice'
      },
      {
        char: '肉',
        pinyin: 'ròu',
        radical: '肉',
        strokeCount: 6,
        shuowen: '肉，胾肉。象形。',
        modernMeaning: '肌肉。也指动物的肉。',
        origin: '肉是象形字，像肉块的形状。',
        example: '猪肉、牛肉、肌肉',
        animation: 'heart'
      },
      {
        char: '蛋',
        pinyin: 'dàn',
        radical: '虫',
        strokeCount: 11,
        shuowen: '蛋，蠃蛋也。从虫，延声。',
        modernMeaning: '卵。也指蛋白质。',
        origin: '蛋是形声字，从虫表意。',
        example: '鸡蛋、蛋糕、鸭蛋',
        animation: 'chicken'
      },
      {
        char: '奶',
        pinyin: 'nǎi',
        radical: '女',
        strokeCount: 5,
        shuowen: '奶，乳也。从女，乃声。',
        modernMeaning: '乳汁。也指祖母。',
        origin: '奶是形声字，从女表意。',
        example: '牛奶、奶奶、奶油',
        animation: 'person'
      },
      {
        char: '糖',
        pinyin: 'táng',
        radical: '米',
        strokeCount: 16,
        shuowen: '糖，饴也。从米，唐声。',
        modernMeaning: '糖分。也指糖果。',
        origin: '糖是形声字，从米表意。',
        example: '糖果、白糖、冰糖',
        animation: 'dots'
      },
      {
        char: '油',
        pinyin: 'yóu',
        radical: '氵',
        strokeCount: 8,
        shuowen: '油，水名。从水，由声。',
        modernMeaning: '油脂。也指滑。',
        origin: '油是形声字，从水表意。',
        example: '石油、加油、油菜',
        animation: 'water'
      },
      {
        char: '盐',
        pinyin: 'yán',
        radical: '皿',
        strokeCount: 10,
        shuowen: '盐，卤也。从卤，监声。',
        modernMeaning: '食盐。也指咸。',
        origin: '盐是形声字，从卤表意。',
        example: '食盐、海盐、盐巴',
        animation: 'dots'
      },
      {
        char: '车',
        pinyin: 'chē',
        radical: '车',
        strokeCount: 4,
        shuowen: '车，舆轮之总名也。象形。',
        modernMeaning: '交通工具。也指机器。',
        origin: '车是象形字，像车的形状。',
        example: '汽车、火车、马车',
        animation: 'car'
      },
      {
        char: '船',
        pinyin: 'chuán',
        radical: '舟',
        strokeCount: 11,
        shuowen: '船，舟也。从舟，铅省声。',
        modernMeaning: '水上交通工具。',
        origin: '船是形声字，从舟表意。',
        example: '轮船、小船、船长',
        animation: 'water'
      },
      {
        char: '路',
        pinyin: 'lù',
        radical: '足',
        strokeCount: 13,
        shuowen: '路，道也。从足，从各。',
        modernMeaning: '道路。也指途径。',
        origin: '路是形声字，从足表意。',
        example: '马路、道路、公路',
        animation: 'walk'
      },
      {
        char: '桥',
        pinyin: 'qiáo',
        radical: '木',
        strokeCount: 10,
        shuowen: '桥，水梁也。从木，乔声。',
        modernMeaning: '桥梁。也指姓。',
        origin: '桥是形声字，从木表意。',
        example: '大桥、木桥、石桥',
        animation: 'mountain'
      },
      {
        char: '房',
        pinyin: 'fáng',
        radical: '户',
        strokeCount: 8,
        shuowen: '房，室在旁也。从户，方声。',
        modernMeaning: '房屋。也指房间。',
        origin: '房是形声字，从户表意。',
        example: '房子、房间、书房',
        animation: 'home'
      },
      {
        char: '屋',
        pinyin: 'wū',
        radical: '尸',
        strokeCount: 9,
        shuowen: '屋，居也。从尸，至声。',
        modernMeaning: '房屋。也指屋子。',
        origin: '屋是形声字，从尸表意。',
        example: '屋子、屋顶、茅屋',
        animation: 'home'
      },
      {
        char: '门',
        pinyin: 'mén',
        radical: '门',
        strokeCount: 3,
        shuowen: '门，闻也。从二户。象形。',
        modernMeaning: '门户。也指家族。',
        origin: '门是象形字，像门的形状。',
        example: '门口、大门、开门',
        animation: 'home'
      },
      {
        char: '窗',
        pinyin: 'chuāng',
        radical: '穴',
        strokeCount: 12,
        shuowen: '窗，通孔也。从穴，囱声。',
        modernMeaning: '窗户。也指天窗。',
        origin: '窗是形声字，从穴表意。',
        example: '窗户、窗口、门窗',
        animation: 'home'
      },
      {
        char: '桌',
        pinyin: 'zhuō',
        radical: '木',
        strokeCount: 10,
        shuowen: '桌，几属。从木，卓声。',
        modernMeaning: '桌子。也指量词。',
        origin: '桌是形声字，从木表意。',
        example: '桌子、书桌、饭桌',
        animation: 'tree'
      },
      {
        char: '椅',
        pinyin: 'yǐ',
        radical: '木',
        strokeCount: 12,
        shuowen: '椅，梓也。从木，奇声。',
        modernMeaning: '椅子。也指山桐子。',
        origin: '椅是形声字，从木表意。',
        example: '椅子、桌椅、轮椅',
        animation: 'tree'
      },
      {
        char: '床',
        pinyin: 'chuáng',
        radical: '广',
        strokeCount: 7,
        shuowen: '床，安身之坐者。从木，爿声。',
        modernMeaning: '床铺。也指井栏。',
        origin: '床是形声字，从木表意。',
        example: '床上、木床、河床',
        animation: 'home'
      },
      {
        char: '灯',
        pinyin: 'dēng',
        radical: '火',
        strokeCount: 6,
        shuowen: '灯，镫也。从火，登声。',
        modernMeaning: '照明器具。也指光明。',
        origin: '灯是形声字，从火表意。',
        example: '灯光、电灯、灯笼',
        animation: 'fire'
      },
      {
        char: '钟',
        pinyin: 'zhōng',
        radical: '钅',
        strokeCount: 9,
        shuowen: '钟，乐钟也。从金，童声。',
        modernMeaning: '时钟。也指计时的器具。',
        origin: '钟是形声字，从金表意。',
        example: '时钟、钟表、闹钟',
        animation: 'metal'
      },
      {
        char: '镜',
        pinyin: 'jìng',
        radical: '钅',
        strokeCount: 16,
        shuowen: '镜，景也。从金，竟声。',
        modernMeaning: '镜子。也指照相。',
        origin: '镜是形声字，从金表意。',
        example: '镜子、眼镜、镜头',
        animation: 'metal'
      },
      {
        char: '书',
        pinyin: 'shū',
        radical: '乛',
        strokeCount: 4,
        shuowen: '书，箸也。从聿，者声。',
        modernMeaning: '书籍。也指书写。',
        origin: '书是形声字，像手持笔书写。',
        example: '书本、读书、书包',
        animation: 'lines'
      },
      {
        char: '笔',
        pinyin: 'bǐ',
        radical: '竹',
        strokeCount: 10,
        shuowen: '笔，秦谓之笔。从聿从竹。',
        modernMeaning: '书写工具。也指书写。',
        origin: '笔是形声字，从竹表意。',
        example: '毛笔、铅笔、钢笔',
        animation: 'tree'
      },
      {
        char: '纸',
        pinyin: 'zhǐ',
        radical: '纟',
        strokeCount: 7,
        shuowen: '纸，絮一苫也。从糸，氏声。',
        modernMeaning: '纸张。也指信件。',
        origin: '纸是形声字，从糸表意。',
        example: '白纸、报纸、纸巾',
        animation: 'tree'
      },
      {
        char: '画',
        pinyin: 'huà',
        radical: '田',
        strokeCount: 8,
        shuowen: '画，界也。象田四界。聿，所以画之。',
        modernMeaning: '图画。也指绘画。',
        origin: '画是象形字，像划分界限。',
        example: '画画、画家、图画',
        animation: 'field'
      },
      {
        char: '歌',
        pinyin: 'gē',
        radical: '欠',
        strokeCount: 14,
        shuowen: '歌，咏也。从欠，哥声。',
        modernMeaning: '歌曲。也指歌唱。',
        origin: '歌是形声字，从欠表意。',
        example: '唱歌、歌声、歌曲',
        animation: 'mouth'
      },
      {
        char: '舞',
        pinyin: 'wǔ',
        radical: '夕',
        strokeCount: 14,
        shuowen: '舞，乐也。用足相背。从舛，象形。',
        modernMeaning: '舞蹈。也指舞动。',
        origin: '舞是象形字，像人跳舞。',
        example: '跳舞、舞蹈、飞舞',
        animation: 'person'
      },
      {
        char: '乐',
        pinyin: 'lè',
        radical: '丿',
        strokeCount: 5,
        shuowen: '乐，五声八音总名。象鼓鞞。木，虡也。',
        modernMeaning: '快乐。也指音乐。',
        origin: '乐是象形字，像乐器。',
        example: '快乐、音乐、乐园',
        animation: 'heart'
      },
      {
        char: '笑',
        pinyin: 'xiào',
        radical: '竹',
        strokeCount: 10,
        shuowen: '笑，喜也。从竹，从夭。',
        modernMeaning: '笑容。也指嘲笑。',
        origin: '笑是形声字，从竹表意。',
        example: '笑容、大笑、笑话',
        animation: 'person'
      },
      {
        char: '哭',
        pinyin: 'kū',
        radical: '口',
        strokeCount: 10,
        shuowen: '哭，哀声也。从吅，狱省声。',
        modernMeaning: '哭泣。也指哀悼。',
        origin: '哭是形声字，从口表意。',
        example: '哭泣、大哭、哭声',
        animation: 'person'
      },
      {
        char: '听',
        pinyin: 'tīng',
        radical: '口',
        strokeCount: 7,
        shuowen: '听，聆也。从口，斤声。',
        modernMeaning: '用耳朵接受声音。也指听从。',
        origin: '听是形声字，从口表意。',
        example: '听话、听见、收听',
        animation: 'mouth'
      },
      {
        char: '说',
        pinyin: 'shuō',
        radical: '讠',
        strokeCount: 9,
        shuowen: '说，释也。从言，兑声。',
        modernMeaning: '说话。也指解释。',
        origin: '说是形声字，从言表意。',
        example: '说话、说明、小说',
        animation: 'mouth'
      },
      {
        char: '话',
        pinyin: 'huà',
        radical: '讠',
        strokeCount: 8,
        shuowen: '话，合会善言也。从言，舌声。',
        modernMeaning: '话语。也指谈话。',
        origin: '话是形声字，从言表意。',
        example: '说话、电话、话语',
        animation: 'mouth'
      },
      {
        char: '语',
        pinyin: 'yǔ',
        radical: '讠',
        strokeCount: 9,
        shuowen: '语，论也。从言，吾声。',
        modernMeaning: '语言。也指说话。',
        origin: '语是形声字，从言表意。',
        example: '语文、语言、成语',
        animation: 'mouth'
      },
      {
        char: '文',
        pinyin: 'wén',
        radical: '文',
        strokeCount: 4,
        shuowen: '文，错画也。象交文。',
        modernMeaning: '文字。也指文化。',
        origin: '文是象形字，像花纹。',
        example: '文化、文字、语文',
        animation: 'lines'
      },
      {
        char: '字',
        pinyin: 'zì',
        radical: '子',
        strokeCount: 6,
        shuowen: '字，乳也。从子在宀下。',
        modernMeaning: '文字。也指名字。',
        origin: '字是形声字，从子表意。',
        example: '汉字、字母、名字',
        animation: 'lines'
      },
      {
        char: '学',
        pinyin: 'xué',
        radical: '子',
        strokeCount: 8,
        shuowen: '学，觉悟也。从教从冖。',
        modernMeaning: '学习。也指学校。',
        origin: '学是形声字，从子表意。',
        example: '学习、学校、学生',
        animation: 'lines'
      },
      {
        char: '校',
        pinyin: 'xiào',
        radical: '木',
        strokeCount: 10,
        shuowen: '校，木囚也。从木，交声。',
        modernMeaning: '学校。也指校正。',
        origin: '校是形声字，从木表意。',
        example: '学校、校园、校长',
        animation: 'tree'
      },
      {
        char: '老',
        pinyin: 'lǎo',
        radical: '老',
        strokeCount: 6,
        shuowen: '老，考也。七十曰老。从人、毛、匕。',
        modernMeaning: '年老。也指陈旧。',
        origin: '老是象形字，像老人。',
        example: '老师、老人、老年',
        animation: 'person'
      },
      {
        char: '师',
        pinyin: 'shī',
        radical: '巾',
        strokeCount: 6,
        shuowen: '师，二千五百人为师。从帀从𠂤。',
        modernMeaning: '老师。也指军队。',
        origin: '师是形声字，从帀表意。',
        example: '老师、教师、师傅',
        animation: 'person'
      },
      {
        char: '爸',
        pinyin: 'bà',
        radical: '父',
        strokeCount: 8,
        shuowen: '爸，父也。从父，巴声。',
        modernMeaning: '父亲。也指爸爸。',
        origin: '爸是形声字，从父表意。',
        example: '爸爸、老爸、干爸',
        animation: 'person'
      },
      {
        char: '妈',
        pinyin: 'mā',
        radical: '女',
        strokeCount: 6,
        shuowen: '妈，母也。从女，马声。',
        modernMeaning: '母亲。也指妈妈。',
        origin: '妈是形声字，从女表意。',
        example: '妈妈、老妈、姑妈',
        animation: 'person'
      },
      {
        char: '哥',
        pinyin: 'gē',
        radical: '口',
        strokeCount: 10,
        shuowen: '哥，声也。从二可。',
        modernMeaning: '兄长。也指哥哥。',
        origin: '哥是形声字，从口表意。',
        example: '哥哥、大哥、表哥',
        animation: 'person'
      },
      {
        char: '姐',
        pinyin: 'jiě',
        radical: '女',
        strokeCount: 8,
        shuowen: '姐，蜀谓母曰姐。从女，且声。',
        modernMeaning: '姐姐。也指女士。',
        origin: '姐是形声字，从女表意。',
        example: '姐姐、大姐、姐妹',
        animation: 'person'
      },
      {
        char: '弟',
        pinyin: 'dì',
        radical: '弓',
        strokeCount: 7,
        shuowen: '弟，韦束之次弟也。从古字之象。',
        modernMeaning: '弟弟。也指次序。',
        origin: '弟是象形字，像绳索缠绕。',
        example: '弟弟、兄弟、弟子',
        animation: 'person'
      },
      {
        char: '妹',
        pinyin: 'mèi',
        radical: '女',
        strokeCount: 8,
        shuowen: '妹，女弟也。从女，未声。',
        modernMeaning: '妹妹。也指女性。',
        origin: '妹是形声字，从女表意。',
        example: '妹妹、姐妹、表妹',
        animation: 'person'
      },
      {
        char: '儿',
        pinyin: 'ér',
        radical: '儿',
        strokeCount: 2,
        shuowen: '儿，孺子也。从儿，象小儿头囟未合。',
        modernMeaning: '儿童。也指儿子。',
        origin: '儿是象形字，像小孩。',
        example: '儿子、儿童、女儿',
        animation: 'person'
      },
      {
        char: '女',
        pinyin: 'nǚ',
        radical: '女',
        strokeCount: 3,
        shuowen: '女，妇人也。象形。',
        modernMeaning: '女性。也指女儿。',
        origin: '女是象形字，像女子。',
        example: '女儿、女人、女性',
        animation: 'person'
      },
      {
        char: '男',
        pinyin: 'nán',
        radical: '田',
        strokeCount: 7,
        shuowen: '男，丈夫也。从田从力。',
        modernMeaning: '男性。也指儿子。',
        origin: '男是会意字，田力为男。',
        example: '男人、男孩、男性',
        animation: 'person'
      },
      {
        char: '爷',
        pinyin: 'yé',
        radical: '父',
        strokeCount: 6,
        shuowen: '爷，俗谓父为爷。从父，耶声。',
        modernMeaning: '祖父。也指爷爷。',
        origin: '爷是形声字，从父表意。',
        example: '爷爷、大爷、老爷',
        animation: 'person'
      },
      {
        char: '奶',
        pinyin: 'nǎi',
        radical: '女',
        strokeCount: 5,
        shuowen: '奶，乳也。从女，乃声。',
        modernMeaning: '祖母。也指乳汁。',
        origin: '奶是形声字，从女表意。',
        example: '奶奶、牛奶、奶油',
        animation: 'person'
      },
      {
        char: '家',
        pinyin: 'jiā',
        radical: '宀',
        strokeCount: 10,
        shuowen: '家，居也。从宀从豭省。',
        modernMeaning: '家庭。也指家乡。',
        origin: '家是形声字，从宀表意。',
        example: '家庭、家乡、国家',
        animation: 'home'
      },
      {
        char: '庭',
        pinyin: 'tíng',
        radical: '广',
        strokeCount: 9,
        shuowen: '庭，宫中也。从广，廷声。',
        modernMeaning: '庭院。也指法庭。',
        origin: '庭是形声字，从广表意。',
        example: '庭院、家庭、法庭',
        animation: 'home'
      },
      {
        char: '园',
        pinyin: 'yuán',
        radical: '囗',
        strokeCount: 7,
        shuowen: '园，所以树果也。从囗，袁声。',
        modernMeaning: '园子。也指游玩。',
        origin: '园是形声字，从囗表意。',
        example: '花园、公园、校园',
        animation: 'flower'
      },
      {
        char: '公',
        pinyin: 'gōng',
        radical: '八',
        strokeCount: 4,
        shuowen: '公，平分也。从八从厶。',
        modernMeaning: '公共。也指公平。',
        origin: '公是形声字，从八表意。',
        example: '公园、公共、公平',
        animation: 'person'
      },
      {
        char: '国',
        pinyin: 'guó',
        radical: '囗',
        strokeCount: 8,
        shuowen: '国，邦也。从囗从或。',
        modernMeaning: '国家。也指国都。',
        origin: '国是形声字，从囗表意。',
        example: '中国、国家、国际',
        animation: 'home'
      },
      {
        char: '乡',
        pinyin: 'xiāng',
        radical: '纟',
        strokeCount: 3,
        shuowen: '乡，国离邑民所封也。从邑，皀声。',
        modernMeaning: '乡村。也指家乡。',
        origin: '乡是形声字，从邑表意。',
        example: '乡村、家乡、故乡',
        animation: 'home'
      },
      {
        char: '城',
        pinyin: 'chéng',
        radical: '土',
        strokeCount: 9,
        shuowen: '城，以盛民也。从土从成。',
        modernMeaning: '城市。也指城墙。',
        origin: '城是形声字，从土表意。',
        example: '城市、长城、城堡',
        animation: 'home'
      },
      {
        char: '市',
        pinyin: 'shì',
        radical: '巾',
        strokeCount: 5,
        shuowen: '市，买卖所之也。从巾。',
        modernMeaning: '市场。也指城市。',
        origin: '市是象形字，像市场。',
        example: '市场、城市、市民',
        animation: 'home'
      },
      {
        char: '村',
        pinyin: 'cūn',
        radical: '木',
        strokeCount: 7,
        shuowen: '村，地名。从木，寸声。',
        modernMeaning: '村庄。也指乡村。',
        origin: '村是形声字，从木表意。',
        example: '村庄、农村、乡村',
        animation: 'home'
      },
      {
        char: '里',
        pinyin: 'lǐ',
        radical: '里',
        strokeCount: 7,
        shuowen: '里，居也。从田从土。',
        modernMeaning: '里面。也指里程。',
        origin: '里是形声字，从田表意。',
        example: '里面、公里、邻里',
        animation: 'home'
      },
      {
        char: '外',
        pinyin: 'wài',
        radical: '夕',
        strokeCount: 5,
        shuowen: '外，远也。从夕从卜。',
        modernMeaning: '外面。与"内"相对。',
        origin: '外是形声字，从夕表意。',
        example: '外面、外国、意外',
        animation: 'home'
      },
      {
        char: '前',
        pinyin: 'qián',
        radical: '刂',
        strokeCount: 9,
        shuowen: '前，不行而进也。从止在舟上。',
        modernMeaning: '前面。与"后"相对。',
        origin: '前是形声字，从止表意。',
        example: '前面、前进、从前',
        animation: 'walk'
      },
      {
        char: '后',
        pinyin: 'hòu',
        radical: '口',
        strokeCount: 6,
        shuowen: '后，继体君也。从口从幺。',
        modernMeaning: '后面。与"前"相对。',
        origin: '后是形声字，从口表意。',
        example: '后面、后来、前后',
        animation: 'walk'
      },
      {
        char: '左',
        pinyin: 'zuǒ',
        radical: '工',
        strokeCount: 5,
        shuowen: '左，手相左助也。从𠂇从工。',
        modernMeaning: '左边。与"右"相对。',
        origin: '左是形声字，从工表意。',
        example: '左边、左右、左手',
        animation: 'hand'
      },
      {
        char: '右',
        pinyin: 'yòu',
        radical: '口',
        strokeCount: 5,
        shuowen: '右，手口相助也。从又从口。',
        modernMeaning: '右边。与"左"相对。',
        origin: '右是形声字，从又表意。',
        example: '右边、左右、右手',
        animation: 'hand'
      },
      {
        char: '东',
        pinyin: 'dōng',
        radical: '一',
        strokeCount: 5,
        shuowen: '东，动也。从木。',
        modernMeaning: '东方。也指主人。',
        origin: '东是象形字，像日在木中。',
        example: '东方、东西、东风',
        animation: 'sun'
      },
      {
        char: '南',
        pinyin: 'nán',
        radical: '十',
        strokeCount: 9,
        shuowen: '南，草木至南方而有任也。',
        modernMeaning: '南方。也指方向。',
        origin: '南是象形字，像乐器。',
        example: '南方、南北、江南',
        animation: 'sun'
      },
      {
        char: '西',
        pinyin: 'xī',
        radical: '西',
        strokeCount: 6,
        shuowen: '西，鸟在巢上。象形。',
        modernMeaning: '西方。也指方向。',
        origin: '西是象形字，像鸟归巢。',
        example: '西方、东西、西瓜',
        animation: 'sun'
      },
      {
        char: '北',
        pinyin: 'běi',
        radical: '匕',
        strokeCount: 5,
        shuowen: '北，乖也。从二人相背。',
        modernMeaning: '北方。也指败北。',
        origin: '北是象形字，像二人相背。',
        example: '北方、北京、南北',
        animation: 'sun'
      },
      {
        char: '方',
        pinyin: 'fāng',
        radical: '方',
        strokeCount: 4,
        shuowen: '方，并船也。象两舟总头形。',
        modernMeaning: '方形。也指方向。',
        origin: '方是象形字，像并船。',
        example: '方向、正方形、方法',
        animation: 'field'
      },
      {
        char: '向',
        pinyin: 'xiàng',
        radical: '口',
        strokeCount: 6,
        shuowen: '向，北出牖也。从宀从口。',
        modernMeaning: '方向。也指朝向。',
        origin: '向是形声字，从口表意。',
        example: '方向、向往、向前',
        animation: 'mouth'
      },
      {
        char: '边',
        pinyin: 'biān',
        radical: '辶',
        strokeCount: 5,
        shuowen: '边，行垂崖也。从辵，臱声。',
        modernMeaning: '边缘。也指旁边。',
        origin: '边是形声字，从辵表意。',
        example: '旁边、边界、海边',
        animation: 'walk'
      },
      {
        char: '旁',
        pinyin: 'páng',
        radical: '方',
        strokeCount: 10,
        shuowen: '旁，溥也。从二，方声。',
        modernMeaning: '旁边。也指广泛。',
        origin: '旁是形声字，从方表意。',
        example: '旁边、身旁、旁观',
        animation: 'home'
      },
      {
        char: '近',
        pinyin: 'jìn',
        radical: '辶',
        strokeCount: 7,
        shuowen: '近，附也。从辵，斤声。',
        modernMeaning: '距离短。与"远"相对。',
        origin: '近是形声字，从辵表意。',
        example: '近处、接近、亲近',
        animation: 'walk'
      },
      {
        char: '远',
        pinyin: 'yuǎn',
        radical: '辶',
        strokeCount: 7,
        shuowen: '远，辽也。从辵，袁声。',
        modernMeaning: '距离长。与"近"相对。',
        origin: '远是形声字，从辵表意。',
        example: '远方、远近、永远',
        animation: 'walk'
      },
      {
        char: '快',
        pinyin: 'kuài',
        radical: '忄',
        strokeCount: 7,
        shuowen: '快，喜也。从心，夬声。',
        modernMeaning: '迅速。也指愉快。',
        origin: '快是形声字，从心表意。',
        example: '快乐、快速、飞快',
        animation: 'heart'
      },
      {
        char: '慢',
        pinyin: 'màn',
        radical: '忄',
        strokeCount: 14,
        shuowen: '慢，惰也。从心，曼声。',
        modernMeaning: '速度低。与"快"相对。',
        origin: '慢是形声字，从心表意。',
        example: '慢走、缓慢、傲慢',
        animation: 'heart'
      },
      {
        char: '高',
        pinyin: 'gāo',
        radical: '高',
        strokeCount: 10,
        shuowen: '高，崇也。象台观高之形。从门、口。与仓、舍同意。',
        modernMeaning: '从下向上距离大。与"低"相对。',
        origin: '高是象形字，像高台的形状。',
        example: '高山、高兴、高大',
        animation: 'tall'
      },
      {
        char: '低',
        pinyin: 'dī',
        radical: '亻',
        strokeCount: 7,
        shuowen: '低，下也。从人，从氐。',
        modernMeaning: '从下向上距离小。与"高"相对。',
        origin: '低是形声字，从人表意。',
        example: '低头、低处、高低',
        animation: 'low'
      },
      {
        char: '长',
        pinyin: 'cháng',
        radical: '长',
        strokeCount: 4,
        shuowen: '长，久远也。从兀，从匕。',
        modernMeaning: '两点距离大。与"短"相对。',
        origin: '长是象形字，像长发的形状。',
        example: '长短、长江、长久',
        animation: 'long'
      },
      {
        char: '短',
        pinyin: 'duǎn',
        radical: '矢',
        strokeCount: 12,
        shuowen: '短，有所长短，以矢为正。从矢，豆声。',
        modernMeaning: '两点距离小。与"长"相对。',
        origin: '短是形声字，从矢表意。',
        example: '长短、短小、短暂',
        animation: 'short'
      },
      {
        char: '多',
        pinyin: 'duō',
        radical: '夕',
        strokeCount: 6,
        shuowen: '多，重也。从重夕。',
        modernMeaning: '数量大。与"少"相对。',
        origin: '多是形声字，从夕表意。',
        example: '多少、很多、众多',
        animation: 'dots'
      },
      {
        char: '少',
        pinyin: 'shǎo',
        radical: '小',
        strokeCount: 4,
        shuowen: '少，不多也。从小丿声。',
        modernMeaning: '数量小。与"多"相对。',
        origin: '少是形声字，从小表意。',
        example: '多少、少年、少数',
        animation: 'dots'
      },
      {
        char: '轻',
        pinyin: 'qīng',
        radical: '车',
        strokeCount: 9,
        shuowen: '轻，轻车也。从车，巠声。',
        modernMeaning: '重量小。与"重"相对。',
        origin: '轻是形声字，从车表意。',
        example: '轻松、年轻、轻视',
        animation: 'car'
      },
      {
        char: '重',
        pinyin: 'zhòng',
        radical: '里',
        strokeCount: 9,
        shuowen: '重，厚也。从壬，東声。',
        modernMeaning: '重量大。与"轻"相对。',
        origin: '重是形声字，从壬表意。',
        example: '重要、重量、重视',
        animation: 'strength'
      },
      {
        char: '好',
        pinyin: 'hǎo',
        radical: '女',
        strokeCount: 6,
        shuowen: '好，美也。从女从子。',
        modernMeaning: '优点多。与"坏"相对。',
        origin: '好是形声字，从女表意。',
        example: '好人、美好、友好',
        animation: 'heart'
      },
      {
        char: '坏',
        pinyin: 'huài',
        radical: '土',
        strokeCount: 7,
        shuowen: '坏，败也。从土，褱声。',
        modernMeaning: '缺点多。与"好"相对。',
        origin: '坏是形声字，从土表意。',
        example: '坏人、破坏、好坏',
        animation: 'ground'
      },
      {
        char: '美',
        pinyin: 'měi',
        radical: '羊',
        strokeCount: 9,
        shuowen: '美，甘也。从羊从大。',
        modernMeaning: '好看。与"丑"相对。',
        origin: '美是形声字，从羊表意。',
        example: '美丽、美好、美好',
        animation: 'flower'
      },
      {
        char: '丑',
        pinyin: 'chǒu',
        radical: '一',
        strokeCount: 4,
        shuowen: '丑，纽也。从手从乙。',
        modernMeaning: '难看。与"美"相对。',
        origin: '丑是象形字，像手。',
        example: '丑恶、丑陋、出丑',
        animation: 'mouth'
      },
      {
        char: '新',
        pinyin: 'xīn',
        radical: '斤',
        strokeCount: 13,
        shuowen: '新，取木也。从斤从木。',
        modernMeaning: '刚出现。与"旧"相对。',
        origin: '新是形声字，从斤表意。',
        example: '新年、新鲜、新闻',
        animation: 'tree'
      },
      {
        char: '旧',
        pinyin: 'jiù',
        radical: '日',
        strokeCount: 5,
        shuowen: '旧，鸱旧，旧留也。从臼，久声。',
        modernMeaning: '过时。与"新"相对。',
        origin: '旧是形声字，从日表意。',
        example: '旧货、陈旧、旧书',
        animation: 'sun'
      },
      {
        char: '早',
        pinyin: 'zǎo',
        radical: '日',
        strokeCount: 6,
        shuowen: '早，晨也。从日在甲上。',
        modernMeaning: '早晨。也指时间早。',
        origin: '早是形声字，从日表意。',
        example: '早上、早晨、早安',
        animation: 'sun'
      },
      {
        char: '晚',
        pinyin: 'wǎn',
        radical: '日',
        strokeCount: 11,
        shuowen: '晚，莫也。从日，免声。',
        modernMeaning: '晚上。也指时间晚。',
        origin: '晚是形声字，从日表意。',
        example: '晚上、夜晚、晚安',
        animation: 'moon'
      },
      {
        char: '早',
        pinyin: 'zǎo',
        radical: '日',
        strokeCount: 6,
        shuowen: '早，晨也。从日在甲上。',
        modernMeaning: '早晨。也指时间早。',
        origin: '早是形声字，从日表意。',
        example: '早上、早晨、早安',
        animation: 'sun'
      },
      {
        char: '午',
        pinyin: 'wǔ',
        radical: '十',
        strokeCount: 4,
        shuowen: '午，牾也。从干从一。',
        modernMeaning: '中午。也指地支。',
        origin: '午是象形字，像舂米。',
        example: '中午、上午、下午',
        animation: 'sun'
      },
      {
        char: '夜',
        pinyin: 'yè',
        radical: '夕',
        strokeCount: 8,
        shuowen: '夜，舍也。从夕，亦省声。',
        modernMeaning: '夜晚。与"昼"相对。',
        origin: '夜是形声字，从夕表意。',
        example: '夜晚、黑夜、半夜',
        animation: 'moon'
      },
      {
        char: '春',
        pinyin: 'chūn',
        radical: '日',
        strokeCount: 9,
        shuowen: '春，推也。从艹从日。',
        modernMeaning: '春季。也指生机。',
        origin: '春是形声字，从日表意。',
        example: '春天、春节、青春',
        animation: 'flower'
      },
      {
        char: '夏',
        pinyin: 'xià',
        radical: '夂',
        strokeCount: 10,
        shuowen: '夏，中国之人也。从夂从页。',
        modernMeaning: '夏季。也指华夏。',
        origin: '夏是形声字，从夂表意。',
        example: '夏天、夏季、华夏',
        animation: 'sun'
      },
      {
        char: '秋',
        pinyin: 'qiū',
        radical: '禾',
        strokeCount: 9,
        shuowen: '秋，禾谷孰也。从禾，𤆅省声。',
        modernMeaning: '秋季。也指庄稼成熟。',
        origin: '秋是形声字，从禾表意。',
        example: '秋天、秋季、秋风',
        animation: 'tree'
      },
      {
        char: '冬',
        pinyin: 'dōng',
        radical: '夂',
        strokeCount: 5,
        shuowen: '冬，四时尽也。从夂从𠔙。',
        modernMeaning: '冬季。也指终了。',
        origin: '冬是形声字，从夂表意。',
        example: '冬天、冬季、冬瓜',
        animation: 'snow'
      },
      {
        char: '年',
        pinyin: 'nián',
        radical: '干',
        strokeCount: 6,
        shuowen: '年，谷孰也。从禾，千声。',
        modernMeaning: '时间单位。也指年龄。',
        origin: '年是象形字，像人背着谷物。',
        example: '年级、新年、年轻',
        animation: 'grain'
      },
      {
        char: '月',
        pinyin: 'yuè',
        radical: '月',
        strokeCount: 4,
        shuowen: '月，阙也。大阴之精。象形。',
        modernMeaning: '月球，月亮。也指月份。',
        origin: '月是象形字，像弯月的形状。',
        example: '月亮、月季、岁月',
        animation: 'moon'
      },
      {
        char: '日',
        pinyin: 'rì',
        radical: '日',
        strokeCount: 4,
        shuowen: '日，实也。太阳之精不亏。从囗一。象形。',
        modernMeaning: '太阳，白天。与"夜"相对。也用于计时。',
        origin: '日是象形字，像太阳的形状，中间的一横表示太阳黑子。',
        example: '日出、日子、今日',
        animation: 'sun'
      },
      {
        char: '星',
        pinyin: 'xīng',
        radical: '日',
        strokeCount: 9,
        shuowen: '星，万物之精，上为列星。',
        modernMeaning: '星星。也指细小的。',
        origin: '星是形声字，从日表意。',
        example: '星星、星球、明星',
        animation: 'star'
      },
      {
        char: '空',
        pinyin: 'kōng',
        radical: '穴',
        strokeCount: 8,
        shuowen: '空，窍也。从穴，工声。',
        modernMeaning: '空虚。也指天空。',
        origin: '空是形声字，从穴表意。',
        example: '空气、天空、空间',
        animation: 'cloud'
      },
      {
        char: '地',
        pinyin: 'dì',
        radical: '土',
        strokeCount: 6,
        shuowen: '地，元气初分，轻清阳为天，重浊阴为地。',
        modernMeaning: '大地。也指土地。',
        origin: '地是形声字，从土表意。',
        example: '地球、地方、土地',
        animation: 'ground'
      }
    ]
  }
]